import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
assert.ok(process.argv[2]&&process.argv[3],'Pass installed Playwright and user Mac Chrome executable; no dependency install.');
const {chromium}=await import(pathToFileURL(process.argv[2]));
const origin='http://127.0.0.1:8818';
const evidence=process.cwd()+'/qa/transactions/evidence';
await mkdir(evidence,{recursive:true});
const profile=await mkdtemp(tmpdir()+'/goat-transactions-synthetic-');
const receipt={head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),method:'Installed Mac Chrome in fresh task-owned profile; fixture on unique localhost port 8818. Native anchors/history, not Next routing.',checks:[],screenshots:[],pageErrors:[],blocked:[],hashes:{}};
const record=(name,data=true)=>{receipt.checks.push({name,data});console.log(name);};
const hash=async p=>createHash('sha256').update(await readFile(p)).digest('hex');
for(const f of ['main.tsx','wire.jsx','wire.css','synthetic-2032.json','synthetic-2031.json','browser.mjs'])receipt.hashes[f]=await hash('qa/transactions/'+f);
const contrast=(a,b)=>{const lum=c=>c.match(/[\d.]+/g).slice(0,3).map(Number).map(n=>n/255).map(n=>n<=.04045?n/12.92:((n+.055)/1.055)**2.4).reduce((sum,n,i)=>sum+n*[.2126,.7152,.0722][i],0);const x=lum(a),y=lum(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);};
let context;
try{
 context=await chromium.launchPersistentContext(profile,{executablePath:process.argv[3],headless:true,viewport:{width:1440,height:1000},reducedMotion:'reduce',args:['--disable-webgl','--remote-debugging-port=0']});
 receipt.browser=context.browser()?.version()??'Installed Chrome persistent context';
 await context.route('**/*',route=>{const r=route.request();if(new URL(r.url()).origin===origin&&r.method()==='GET')return route.continue();receipt.blocked.push({url:r.url(),method:r.method()});return route.abort();});
 const page=context.pages()[0];page.on('pageerror',e=>receipt.pageErrors.push(e.message));
 const visit=async query=>{await page.goto(origin+'/transactions?'+query,{waitUntil:'networkidle'});await page.locator('main').waitFor();await page.evaluate(()=>document.fonts.ready);};
 const shot=async name=>{const path=evidence+'/'+name+'.png';await page.screenshot({path,fullPage:false});receipt.screenshots.push({file:name+'.png',sha256:await hash(path)});};
 const geometry=async()=>{
  const g=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,controls:[...document.querySelectorAll('button,select,input,.control,summary')].filter(e=>e.getBoundingClientRect().height>0).map(e=>{const r=e.getBoundingClientRect();return {name:e.textContent||e.getAttribute('aria-label'),x:r.x,right:r.right,width:r.width,height:r.height};}),clipped:[...document.querySelectorAll('main p,main h1,main h2,main h3,main dd,main a,main button')].filter(e=>e.getBoundingClientRect().height>0&&e.scrollWidth>e.clientWidth+1).map(e=>e.textContent),text:document.querySelector('main').textContent}));
  assert.ok(g.scroll<=g.width+1,JSON.stringify(g));assert.ok(!g.text.includes('NaN'));assert.deepEqual(g.clipped,[]);
  for(const c of g.controls){assert.ok(c.height>=43.5&&c.width>=43.5,JSON.stringify(c));assert.ok(c.x>=-1&&c.right<=g.width+1,JSON.stringify(c));}return {width:g.width,scroll:g.scroll,controls:g.controls.length};
 };

 // Repaired production surface/transform over invented inputs.
 await visit('variant=source&season=2031&type=trade&team=703');await page.getByRole('button',{name:'Trades',exact:true}).click();await page.getByLabel('Filter by team').selectOption('703');assert.match(await page.locator('p[aria-live]').textContent(),/^5 transactions/);record('Repaired source includes declared pick-only trade participants');
 await visit('variant=source&season=2031&type=waiver');assert.match(await page.locator('p[aria-live]').textContent(),/^4 transactions/);record('Repaired source excludes failed waiver activity');
 await visit('season=2031&type=trade&team=703&theme=light');assert.match(await page.getByRole('status').textContent(),/^5 moves/);record('Prototype includes invented pick-only trades in team filter');
 await visit('season=2031&type=waiver');assert.match(await page.getByRole('status').textContent(),/^4 moves/);record('Prototype separates the invented failed waiver from completed wire');
 await visit('season=2032&team=707&utm=retained#wire');assert.equal(await page.getByLabel('Team in this league').inputValue(),'707');assert.match(await page.getByRole('status').textContent(),/^3 moves/);
 await page.reload({waitUntil:'networkidle'});assert.match(await page.getByRole('status').textContent(),/^3 moves/);await page.getByRole('link',{name:'Copper Comets',exact:true}).first().click();assert.equal(new URL(page.url()).pathname,'/teams/707');await page.goBack({waitUntil:'networkidle'});assert.equal(await page.getByLabel('Team in this league').inputValue(),'707');assert.match(await page.getByRole('status').textContent(),/^3 moves/);await shot('team707-back-restored');record('Copper Comets 3 → profile → Back → 3; direct load and reload preserve filter');
 await page.goForward({waitUntil:'networkidle'});assert.equal(new URL(page.url()).pathname,'/teams/707');await page.goBack({waitUntil:'networkidle'});
 await page.getByRole('button',{name:/Trades/}).click();let u=new URL(page.url());assert.equal(u.searchParams.get('type'),'trade');assert.equal(u.searchParams.get('team'),'707');assert.equal(u.searchParams.get('utm'),'retained');assert.equal(u.hash,'#wire');await page.getByRole('button',{name:'Clear filters',exact:true}).click();u=new URL(page.url());assert.equal(u.searchParams.get('team'),null);assert.equal(u.searchParams.get('type'),null);assert.equal(u.searchParams.get('utm'),'retained');assert.equal(u.hash,'#wire');record('Canonical team/type query, reset, unrelated query and hash conservation');
 await visit('team=unknown&type=nonsense');assert.equal(await page.getByLabel('Team in this league').inputValue(),'all');assert.match(await page.getByRole('status').textContent(),/^26 moves/);record('Unknown team/type fall back to All without fetching');
 await visit('season=2032&player=demo-player-lyra');assert.match(await page.getByRole('status').textContent(),/^2 moves/);await page.getByLabel('From',{exact:true}).fill('2032-12-05');assert.match(await page.getByRole('status').textContent(),/^1 move/);await page.getByLabel('Through',{exact:true}).fill('2032-12-01');assert.match(await page.getByRole('alert').textContent(),/on or after/);record('Player and UTC date filters; invalid range has explicit state');
 await visit('season=2032&theme=light');assert.equal(await page.locator('[data-transaction]').count(),12);await page.getByRole('button',{name:'Next',exact:true}).click();assert.match(await page.locator('.pagination').textContent(),/Page 2 of 3/);await page.reload({waitUntil:'networkidle'});assert.match(await page.locator('.pagination').textContent(),/Page 2 of 3/);record('12-row pagination, page URL and reload restoration');
 await visit('season=2031&type=trade&detail=demo-2031-pick-trade-2&theme=light');const detail=page.locator('#detail-demo-2031-pick-trade-2');assert.match(await detail.textContent(),/round 4/);assert.match(await detail.textContent(),/round 5/);assert.match(await detail.textContent(),/Received/);assert.match(await detail.textContent(),/Sent/);assert.equal(await detail.locator('a[href*="/player/"]').count(),0);await shot('desktop-pick-only-detail');record('Synthetic pick-only sent/received/season/original-roster/ID preserved; no fabricated players in a pick-only move');
 await page.getByRole('button',{name:'Close detail',exact:true}).click();await page.waitForFunction(()=>document.activeElement?.closest('[data-transaction]')?.getAttribute('data-transaction')==='demo-2031-pick-trade-2');const trigger=page.locator('[data-transaction="demo-2031-pick-trade-2"]').getByRole('button',{name:'Details',exact:true});assert.equal(await trigger.evaluate(e=>document.activeElement===e),true);await trigger.press('Enter');assert.equal(await page.locator('#detail-demo-2031-pick-trade-2').count(),1);await page.getByRole('button',{name:'Hide detail',exact:true}).press('Escape');assert.equal(await detail.count(),0);record('Keyboard detail open/Escape/close restoration');
 for(const width of [1440,768,390,320])for(const enlarged of [false,true])for(const theme of ['light','dark','system']){
  await page.setViewportSize({width,height:1000});await visit(`season=2031&type=trade&detail=demo-2031-player-trade-1&theme=${theme}`);await page.evaluate(enlarged=>document.documentElement.style.fontSize=enlarged?'200%':'100%',enlarged);const g=await geometry();record(`${width}px ${enlarged?'200%':'100%'} text ${theme} populated trade geometry`,g);if(!enlarged&&theme!=='system'&&[1440,390,320].includes(width))await shot(`${width}-${theme}-trade`);
 }
 for(const state of ['loading','error','empty']){await page.setViewportSize({width:320,height:844});await visit(`season=2032&state=${state}&theme=dark`);await geometry();await shot('320-'+state);if(state==='error'){await page.getByRole('button',{name:'Retry',exact:true}).click();assert.equal(await page.locator('[data-transaction]').count(),12);}record('320px '+state+' state and recovery');}
 await visit('season=2031&team=707');assert.equal(await page.getByLabel('Team in this league').locator('option:checked').textContent(),'Copper Lanterns');assert.match(await page.locator('.context-note').textContent(),/Demo Ember/);assert.ok(!(await page.locator('.context-note').textContent()).includes('Copper Comets'));record('Archived Copper Lanterns/Demo Ember labels retained independently of current identity');
 await page.setViewportSize({width:320,height:844});await visit('season=2032&theme=light');await page.evaluate(()=>{document.querySelector('.coverage').textContent='Synthetic long-name stress case; synthetic fixture unchanged';for(const e of document.querySelectorAll('.move-content a'))e.textContent+=' AnExtraordinarilyLongUnbrokenTeamOrPlayerName'.repeat(2);});await geometry();record('320px synthetic unbroken long-name stress reflows without clipping');
 for(const theme of ['light','dark']){await visit('theme='+theme);const colors=await page.evaluate(()=>{const r=document.querySelector('.review'),c=document.querySelector('.coverage');return {ink:getComputedStyle(r).color,muted:getComputedStyle(c).color,bg:getComputedStyle(r).backgroundColor,focus:getComputedStyle(r).getPropertyValue('--gh-focus').trim()};});assert.ok(contrast(colors.ink,colors.bg)>=4.5);assert.ok(contrast(colors.muted,colors.bg)>=4.5);record(theme+' actual rendered normal/secondary text contrast',{...colors,inkRatio:contrast(colors.ink,colors.bg),mutedRatio:contrast(colors.muted,colors.bg)});}

 await page.goto(origin+'/teams',{waitUntil:'networkidle'});await page.getByRole('link',{name:'Copper Comets',exact:true}).click();assert.equal(new URL(page.url()).pathname,'/teams/707');await page.getByRole('link',{name:'Transactions for Copper Comets',exact:true}).click();assert.equal(new URL(page.url()).searchParams.get('team'),'707');assert.match(await page.getByRole('status').textContent(),/^3 moves/);await page.getByRole('link',{name:'Teams',exact:true}).click();assert.equal(new URL(page.url()).pathname,'/teams');await page.goBack({waitUntil:'networkidle'});assert.match(await page.getByRole('status').textContent(),/^3 moves/);await page.goBack({waitUntil:'networkidle'});assert.equal(new URL(page.url()).pathname,'/teams/707');record('Native fixture Teams → named profile → explicitly filtered Transactions → Teams and Back');
 await visit('season=2032&team=707&detail=demo-stale-link');assert.equal(await page.getByRole('alert').count(),1);record('Unknown detail ID has explicit stale-link state');
 await visit('theme=system');await page.emulateMedia({colorScheme:'dark'});await page.locator('.review.dark').waitFor({state:'attached'});assert.equal(await page.locator('.review.dark').count(),1);await page.emulateMedia({colorScheme:'light'});await page.locator('.review.dark').waitFor({state:'detached'});assert.equal(await page.locator('.review.dark').count(),0);record('System appearance follows preference changes without changing the URL');
 // Actual browser zoom, independently from text enlargement.
 await page.goto('chrome://settings/appearance',{waitUntil:'domcontentloaded'});const zoom=page.getByRole('combobox',{name:/Page zoom/i});await zoom.selectOption({label:'200%'});assert.equal((await zoom.locator('option:checked').textContent()).trim(),'200%');await page.setViewportSize({width:1440,height:900});await visit('season=2032&theme=light');const native=await geometry();await shot('native-200-percent');record('Actual Chrome 200% page zoom setting',native);
 assert.deepEqual(receipt.pageErrors,[]);assert.deepEqual(receipt.blocked,[]);
 receipt.result='PASS';
}catch(e){receipt.result='FAIL';receipt.failure=e.stack;throw e;}finally{await context?.close();await rm(profile,{recursive:true,force:true});await writeFile(evidence+'/receipt.json',JSON.stringify(receipt,null,2)+'\n');}
