import {useEffect, useRef, useState} from 'react';
import Link from 'next/link';
import {PlayerName} from '@/ui/PlayerRow';
import current from './synthetic-2032.json';
import archive from './synthetic-2031.json';

// Presentation experiment over entirely invented demonstration records. No loader, domain,
// auth or production route changes. Unknown fields remain unknown.
const fixtures={'2032':current,'2031':archive};
const kinds=['all','trade','add','drop','waiver','free_agent'];
const labels={all:'All moves',trade:'Trades',add:'Adds',drop:'Drops',waiver:'Waivers',free_agent:'Free agents'};
const size=12;
const day=t=>Number.isFinite(t)&&!Number.isNaN(new Date(t).valueOf())?new Date(t).toISOString().slice(0,10):'';
const date=t=>day(t)?new Intl.DateTimeFormat('en-US',{year:'numeric',month:'short',day:'numeric',timeZone:'UTC'}).format(t):'Date unavailable';
const participants=t=>[...new Set([...(t.roster_ids??[]),...Object.values(t.adds??{}),...Object.values(t.drops??{}),...(t.draft_picks??[]).flatMap(p=>[p.owner_id,p.previous_owner_id]),...(t.waiver_budget??[]).flatMap(b=>[b.sender,b.receiver])].filter(Number.isFinite))].map(String);
const typeLabel=t=>t.type==='trade'?'Trade':t.type==='waiver'?'Waiver':Object.keys(t.adds??{}).length?(Object.keys(t.drops??{}).length?'Add + drop':'Add'):'Drop';
function read(){const p=new URLSearchParams(location.search);const season=fixtures[p.get('season')]?p.get('season'):'2032';const sourceType=p.get('type');const kind=sourceType?(['trade','waiver','free_agent'].includes(sourceType)?sourceType:'all'):(kinds.includes(p.get('kind'))?p.get('kind'):'all');return {season,kind,team:fixtures[season].teams.some(t=>t.id===p.get('team'))?p.get('team'):'all',player:p.get('player')??'',from:p.get('from')??'',to:p.get('to')??'',page:Math.max(1,Math.min(100,Number(p.get('page'))||1)),detail:p.get('detail')??'',theme:['light','dark','system'].includes(p.get('theme'))?p.get('theme'):'system',state:p.get('state')??'populated'};}
function href(s){const p=new URLSearchParams(location.search);for(const key of ['season','kind','type','team','player','from','to','page','detail','theme','state'])p.delete(key);for(const [k,v] of Object.entries(s)){if(v&&!(k==='page'&&v===1)&&!(k==='kind'&&v==='all')&&!(k==='team'&&v==='all')&&!(k==='state'&&v==='populated'))p.set(k==='kind'&&['trade','waiver','free_agent'].includes(v)?'type':k,String(v));}return '/transactions'+(p.size?'?'+p:'')+location.hash;}
const pl=(id,names)=><PlayerName key={id} player={{id,fullName:names[id]??`Player ${id}`}}/>;
function Players({ids,names}){return <>{ids.map((id,i)=><span key={id}>{i>0?', ':''}{pl(id,names)}</span>)}</>;}
function TeamName({id,fixture}){const team=fixture.teams.find(t=>t.id===String(id));return <a href={`/teams/${id}`}>{team?.name??`Roster ${id}`}</a>;}
function assets(t,id,direction,fixture){
 const map=direction==='received'?t.adds:t.drops;
 const players=Object.entries(map??{}).filter(([,rid])=>String(rid)===id).map(([pid])=>pid);
 const picks=(t.draft_picks??[]).filter(p=>String(direction==='received'?p.owner_id:p.previous_owner_id)===id);
 const faab=(t.waiver_budget??[]).filter(b=>String(direction==='received'?b.receiver:b.sender)===id&&Number.isFinite(b.amount));
 return <>{players.length>0&&<Players ids={players} names={fixture.playerNames}/>}{picks.map((p,i)=><span className="asset" key={i}>{p.season} round {p.round} · original <TeamName id={p.roster_id} fixture={fixture}/></span>)}{faab.map((b,i)=><span className="asset" key={i}>${b.amount} FAAB</span>)}{players.length+picks.length+faab.length===0&&<span className="muted">No assets recorded</span>}</>;
}
function Detail({t,fixture,state,update}){
 const ids=participants(t);const bid=t.settings?.waiver_bid;
 return <div className="move-detail" id={`detail-${t.transaction_id}`}>
  {t.type==='trade'?<div className="trade-sides">{ids.map(id=><section key={id}><h3><TeamName id={id} fixture={fixture}/></h3><p className="manager">Managed by {fixture.teams.find(x=>x.id===id)?.managerName??'manager unavailable'} · {fixture.season} label</p><div className="asset-group"><b>Received</b><div>{assets(t,id,'received',fixture)}</div></div><div className="asset-group"><b>Sent</b><div>{assets(t,id,'sent',fixture)}</div></div></section>)}</div>:<p>{Object.keys(t.adds??{}).length>0&&<>Added <Players ids={Object.keys(t.adds)} names={fixture.playerNames}/>. </>}{Object.keys(t.drops??{}).length>0&&<>Dropped <Players ids={Object.keys(t.drops)} names={fixture.playerNames}/>. </>}{t.type==='waiver'&&(Number.isFinite(bid)?<>FAAB bid: ${bid}.</>:<>FAAB bid not supplied by source.</>)}</p>}
  <dl className="provenance"><div><dt>Created (UTC)</dt><dd>{day(t.created)?new Date(t.created).toISOString().replace('T',' ').replace('Z',''):'Unavailable'}</dd></div><div><dt>Last source update (UTC)</dt><dd>{day(t.status_updated)?new Date(t.status_updated).toISOString().replace('T',' ').replace('Z',''):'Unavailable'}</dd></div><div><dt>Season / source week</dt><dd>{fixture.season} / {Number.isFinite(t.leg)?t.leg:'Unavailable'}</dd></div><div><dt>Transaction ID</dt><dd>{t.transaction_id}</dd></div><div><dt>League ID</dt><dd>{fixture.leagueId}</dd></div><div><dt>Source status</dt><dd>{t.status??'Not reported'}</dd></div></dl>
  <div className="detail-actions"><a className="control" href={href({...state,detail:t.transaction_id})}>Link to this move</a><a className="control" href={`/fixture-source?season=${fixture.season}&week=${t.leg}`} target="_blank" rel="noreferrer">Synthetic source</a><button onClick={()=>update({detail:''},true)}>Close detail</button></div>
 </div>;
}
export function Wire(){
 const [state,setState]=useState(read);const [moreOpen,setMoreOpen]=useState(()=>{const s=read();return Boolean(s.player||s.from||s.to||s.kind==='free_agent');});const [systemDark,setSystemDark]=useState(()=>matchMedia('(prefers-color-scheme: dark)').matches);const heading=useRef(null);const triggers=useRef(new Map());
 useEffect(()=>{const pop=()=>{const s=read();setState(s);if(s.player||s.from||s.to||s.kind==='free_agent')setMoreOpen(true);};addEventListener('popstate',pop);const mq=matchMedia('(prefers-color-scheme: dark)');const change=()=>setSystemDark(mq.matches);mq.addEventListener('change',change);return()=>{removeEventListener('popstate',pop);mq.removeEventListener('change',change);};},[]);
 const fixture=fixtures[state.season];
 const update=(patch,restore=false)=>{const next={...state,...patch};history.pushState(null,'',href(next));setState(next);if(restore&&state.detail)requestAnimationFrame(()=>triggers.current.get(state.detail)?.focus());};
 const moves=fixture.raw.filter(t=>['trade','waiver','free_agent'].includes(t.type)&&t.status==='complete');
 const filtered=moves.filter(t=>(state.kind==='all'||(state.kind==='trade'?t.type==='trade':['waiver','free_agent'].includes(state.kind)?t.type===state.kind:t.type!=='trade'&&Object.keys((state.kind==='add'?t.adds:t.drops)??{}).length>0))&&(state.team==='all'||participants(t).includes(state.team))&&(!state.player||[...Object.keys(t.adds??{}),...Object.keys(t.drops??{})].includes(state.player))&&(!state.from||day(t.created)>=state.from)&&(!state.to||day(t.created)<=state.to));
 const pages=Math.max(1,Math.ceil(filtered.length/size));const linked=moves.find(t=>t.transaction_id===state.detail);const selected=filtered.find(t=>t.transaction_id===state.detail);const page=selected?Math.floor(filtered.indexOf(selected)/size)+1:Math.min(state.page,pages);const shown=filtered.slice((page-1)*size,page*size);
 const dark=state.theme==='dark'||state.theme==='system'&&systemDark;
 const team=fixture.teams.find(t=>t.id===state.team);
 const filteredState=state.team!=='all'||state.kind!=='all'||state.player||state.from||state.to;
 const route=location.pathname;
 const setFilter=patch=>update({...patch,page:1,detail:''});
 return <div className={`review ${dark?'dark':''}`}>
  <div className="review-toolbar"><span>GOAT Hoopers · isolated presentation review</span><label>Appearance <select aria-label="Appearance" value={state.theme} onChange={e=>update({theme:e.target.value})}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label></div>
  <main className="wire" onKeyDown={e=>{if(e.key==='Escape'&&state.detail){e.preventDefault();update({detail:''},true);}}}>
  {route==='/fixture-source'?<><h1>Synthetic source fixture</h1><p>Invented demonstration data. No Sleeper request.</p><a className="control" href={href(state)}>Transactions</a><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(fixture.raw,null,2)}</pre></>:route.startsWith('/teams')||route.startsWith('/player')?<><p className="eyebrow">Fixture navigation destination</p><h1>{route==='/teams'?'Teams':route.startsWith('/player')?fixture.playerNames[route.split('/').at(-1)]??'Player profile':fixture.teams.find(t=>t.id===route.split('/').at(-1))?.name??'Team profile'}</h1><p>Navigation only. Shared header and public profiles are owned separately.</p>{route==='/teams'&&<ul className="fixture-directory">{fixture.teams.map(t=><li key={t.id}><Link className="control" href={`/teams/${t.id}`}>{t.name}</Link></li>)}</ul>}<div className="detail-actions"><Link className="control" href="/teams">Teams</Link><a className="control" href={href({...state,team:route.startsWith('/teams/')?route.split('/').at(-1):'all'})}>{route.startsWith('/teams/')?`Transactions for ${fixture.teams.find(t=>t.id===route.split('/').at(-1))?.name??'this franchise'}`:'League transactions'}</a><button onClick={()=>history.back()}>Back</button></div></>:<>
   <div className="page-intro"><div><p className="eyebrow">League wire</p><h1 ref={heading} tabIndex={-1}>Transactions</h1></div><Link className="control" href="/teams">Teams</Link></div>
   <p className="coverage">Synthetic {fixture.season} week 1 demo · {state.season==='2031'?'invented archive sample':'26 invented current-season moves'} · dates in UTC</p>
   <div className="type-tabs" role="group" aria-label="Move type">{kinds.filter(k=>k!=='free_agent').map(kind=><button key={kind} aria-pressed={state.kind===kind} onClick={()=>setFilter({kind})}>{labels[kind]} <span>{moves.filter(t=>kind==='all'||(kind==='trade'?t.type==='trade':['waiver','free_agent'].includes(kind)?t.type===kind:t.type!=='trade'&&Object.keys((kind==='add'?t.adds:t.drops)??{}).length>0)).length}</span></button>)}</div>
   <form className="filters" onSubmit={e=>e.preventDefault()}>
    <label>Season<select value={state.season} onChange={e=>setFilter({season:e.target.value,team:'all',player:'',from:'',to:''})}><option value="2032">2032 · demo</option><option value="2031">2031 · demo</option></select></label>
    <label>Team in this league<select value={state.team} onChange={e=>setFilter({team:e.target.value})}><option value="all">All teams</option>{[...fixture.teams].sort((a,b)=>a.name.localeCompare(b.name)).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
   </form>
   <details className="extra-filters" open={moreOpen} onToggle={e=>setMoreOpen(e.currentTarget.open)}><summary>Player, dates and source type{state.player||state.from||state.to||state.kind==='free_agent'?' · filtered':''}</summary><div className="more-fields">
    <label>Player<select value={state.player} onChange={e=>setFilter({player:e.target.value})}><option value="">All players</option>{Object.entries(fixture.playerNames).sort((a,b)=>a[1].localeCompare(b[1])).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
    <label>From<input type="date" value={state.from} onChange={e=>setFilter({from:e.target.value})}/></label><label>Through<input type="date" value={state.to} onChange={e=>setFilter({to:e.target.value})}/></label>

    <label>Source type<select value={['trade','waiver','free_agent'].includes(state.kind)?state.kind:'all'} onChange={e=>setFilter({kind:e.target.value})}><option value="all">All source types</option><option value="trade">Trade</option><option value="waiver">Waiver</option><option value="free_agent">Free agent</option></select></label>
   </div></details>
   <div className="result-bar"><p role="status">{filtered.length} {filtered.length===1?'move':'moves'}{team?` involving ${team.name}`:' across the league'}{state.kind!=='all'?` · ${labels[state.kind].toLowerCase()}`:''}</p><div><a className="control" href={href({...state,detail:''})}>Link to this view</a>{filteredState&&<button onClick={()=>setFilter({kind:'all',team:'all',player:'',from:'',to:''})}>Clear filters</button>}</div></div>
   {team&&<p className="context-note">League Transactions filtered to {team.name} · {fixture.season} manager: {team.managerName}</p>}
   {state.from&&state.to&&state.from>state.to?<p role="alert">Choose a Through date on or after From.</p>:state.state==='loading'?<div className="state-box" role="status"><h2>Loading the wire…</h2><p>Fetching the selected source period.</p></div>:state.state==='error'?<div className="state-box" role="alert"><h2>The wire is unavailable</h2><p>This is a retrieval failure. Your filters are retained.</p><button onClick={()=>update({state:'populated'})}>Retry</button></div>:state.state==='empty'||!filtered.length?<div className="state-box"><h2>{filteredState?'No moves match these filters':'No completed moves in this period'}</h2><p>{filteredState?'Try another player, team or date range.':'A quiet source period is different from a failed request.'}</p></div>:<>
    <ol className="move-list">{shown.map(t=><li key={t.transaction_id} data-transaction={t.transaction_id} className={state.detail===t.transaction_id?'selected':''}>
     <div className="move-row"><div className="date-cell"><time dateTime={day(t.created)}>{date(t.created)}</time><span>{t.leg===0?'Preseason':`Source week ${t.leg}`}</span></div><div className="move-content"><b className="kind" data-kind={t.type}>{typeLabel(t)}</b>{t.type==='trade'?<div className="trade-summary">{participants(t).map(id=><p key={id}><TeamName id={id} fixture={fixture}/><span className="verb"> received </span>{assets(t,id,'received',fixture)}</p>)}</div>:<p><TeamName id={participants(t)[0]} fixture={fixture}/>{Object.keys(t.adds??{}).length>0&&<> added <Players ids={Object.keys(t.adds)} names={fixture.playerNames}/></>}{Object.keys(t.adds??{}).length>0&&Object.keys(t.drops??{}).length>0?'; ':''}{Object.keys(t.drops??{}).length>0&&<> dropped <Players ids={Object.keys(t.drops)} names={fixture.playerNames}/></>}</p>}</div><button ref={el=>{if(el)triggers.current.set(t.transaction_id,el);}} aria-expanded={state.detail===t.transaction_id} aria-controls={`detail-${t.transaction_id}`} onClick={()=>update({detail:state.detail===t.transaction_id?'':t.transaction_id})}>{state.detail===t.transaction_id?'Hide detail':'Details'}</button></div>
     {state.detail===t.transaction_id&&<Detail t={t} fixture={fixture} state={state} update={update}/>}
    </li>)}</ol>
    <nav className="pagination" aria-label="Transactions pages"><button disabled={page===1} onClick={()=>{update({page:page-1,detail:''});heading.current?.focus();}}>Previous</button><p>Page {page} of {pages} · {Math.min((page-1)*size+1,filtered.length)}–{Math.min(page*size,filtered.length)} of {filtered.length}</p><button disabled={page===pages} onClick={()=>{update({page:page+1,detail:''});heading.current?.focus();}}>Next</button></nav>
   </>}
   <p className="coverage">Completed trades, waivers and free-agent moves only. {fixture.raw.filter(t=>t.status!=='complete').length} failed record(s) retained in the source fixture. Unknown demo player names retain their invented ID.</p>
   {state.detail&&!selected&&<p role="alert">{linked?'This move is outside these filters.':'This transaction is not in the synthetic period.'} {linked&&<button onClick={()=>update({kind:'all',team:'all',player:'',from:'',to:'',page:1})}>Show linked move</button>}<button onClick={()=>update({detail:''})}>Dismiss</button></p>}
   <details className="qa-controls"><summary>Review states and evidence</summary><p>This prototype adds proposed URL state. Profile/player links use invented IDs and resolve only to local fixture adapters. It does not claim production or Next routing integration.</p><label>State <select aria-label="Review state" value={state.state} onChange={e=>update({state:e.target.value})}><option value="populated">Populated</option><option value="loading">Loading</option><option value="error">Error</option><option value="empty">Empty</option></select></label><a className="control" href={`/transactions?variant=source&season=${state.season}`}>Repaired source component</a></details>
  </>}
  </main>
 </div>;
}
