/** Client-safe AI Decides contract. Provider probabilities are not sports odds. */
export const AI_DECISION_MODEL = "gpt-6-luna" as const;
export const AI_CUSTOM_PROMPT_VERSION = "goat-custom-choice-v1";
export const AI_WEEKLY_PROMPT_VERSION = "goat-weekly-lock-in-v1";
export const AI_PROBABILITY_LABEL = "Model probability — not calibrated sports odds" as const;

/** Drafts need no account. Only an authenticated server run spends a budget. */
export type AiDecideRequest =
  | { kind: "custom"; prompt: string; choices: string[] }
  | { kind: "matchup"; teamIds: [string, string] };

/** Evidence is formatted from supplied facts, never generated by the model. */
export type AiDecisionResult = {
  model: typeof AI_DECISION_MODEL;
  promptVersion: string;
  choice: string;
  confidence: number;
  probabilities: { choice: string; probability: number }[];
  evidence: string[];
  probabilityLabel: typeof AI_PROBABILITY_LABEL;
  snapshot: AiSnapshotMetadata | null;
};

export type AiSnapshotMetadata = {
  hash: string;
  model: typeof AI_DECISION_MODEL;
  promptVersion: string;
  capturedAt: string;
  cutoffAt: string;
  startsAt: string;
  endsAt: string;
  statsSeason: string;
  scoringMode: AiWeeklyInput["scoringMode"];
  baselineVersion: string;
};

export type AiFailureStatus = "unavailable" | "invalid" | "unauthenticated" | "rate_limited" | "busy" | "refused" | "timeout";
export type AiDecideResponse =
  | { status: "ready"; result: AiDecisionResult }
  | { status: AiFailureStatus; code: string; message: string; retryAfterSeconds?: number };

/** This comparison has no schedule adjustment and is not a weekly score forecast. */
export type AiBaseline = {
  version: string;
  label: string;
  teamValues: { teamId: string; value: number | null }[];
  pick: string | null;
};

export type AiWeeklyPick = {
  matchupId: string;
  teamIds: [string, string];
  status: "ready" | "unavailable";
  message: string;
  result: AiDecisionResult | null;
  evidence: string[];
  baseline: AiBaseline | null;
};

export type AiWeeklySlate = {
  leagueId: string;
  season: string;
  week: number;
  status: "ready" | "unavailable" | "stale";
  message: string;
  generatedAt: string | null;
  matchups: AiWeeklyPick[];
  snapshot: AiSnapshotMetadata | null;
};

export type AiDecidesData = {
  availability: { status: "available" | "unavailable"; code: string; message: string };
  weekly: AiWeeklySlate;
};

/** Inputs retained once per week. No post-cutoff inputs or observed outcomes. */
export type AiWeeklyInput = {
  leagueId: string;
  season: string;
  week: number;
  capturedAt: string;
  cutoffAt: string;
  startsAt: string;
  endsAt: string;
  phase: "pre" | "regular" | "post";
  scoringMode: "lock_in" | "game_pick" | "unknown";
  scoring: Record<string, number>;
  starterSlots: string[];
  statsSeason: string;
  statsAvailableAt: string;
  matchups: { matchupId: string; teamIds: [string, string] }[];
  teams: {
    teamId: string;
    starters: string[];
    reserve: string[];
    taxi: string[];
    eligibilityKnown: boolean;
    players: { playerId: string; priorFantasyPpg: number | null; priorGames: number | null }[];
  }[];
};

/** Append-only evaluation record, deliberately outside the prediction snapshot. */
export type AiWeeklyOutcome = {
  matchupId: string;
  recordedAt: string;
  final: true;
  teamPoints: { teamId: string; points: number }[];
};
