/** Client-safe AI Decides contract. Provider probabilities are not sports odds. */
export const AI_DECISION_MODEL = "gpt-6-luna" as const;
export const AI_CUSTOM_PROMPT_VERSION = "goat-custom-choice-v1";
export const AI_LEAGUE_ROSTER_PROMPT_VERSION = "goat-league-roster-v1";
export const AI_WEEKLY_PROMPT_VERSION = "goat-weekly-lock-in-v1";
export const AI_LINEUP_PREVIEW_PROMPT_VERSION = "goat-lineup-preview-v2";
export const AI_PROBABILITY_LABEL = "Model probability — not calibrated sports odds" as const;

/** Drafts need no account. Only an authenticated server run spends a budget. */
export type AiDecideRequest =
  | { kind: "custom"; prompt: string; choices: string[] }
  /** Explicit choice-index → roster-ID mapping; the server verifies canonical names. */
  | { kind: "league"; prompt: string; choices: [string, string]; teamIds: [string, string] }
  | { kind: "matchup"; teamIds: [string, string] };

/** Evidence is formatted from supplied facts, never generated by the model. */
export type AiDecisionResult = {
  model: string;
  promptVersion: string;
  choice: string;
  confidence: number;
  probabilities: { choice: string; probability: number }[];
  evidence: string[];
  probabilityLabel: typeof AI_PROBABILITY_LABEL;
  snapshot: AiSnapshotMetadata | null;
  /** On-demand current-roster evidence; separate from immutable weekly snapshots. */
  leagueContext?: AiLeagueContextMetadata;
};

export type AiLeagueContextMetadata = {
  hash: string;
  source: "sleeper";
  leagueId: string;
  capturedAt: string;
  season: string;
  phase: "pre" | "regular" | "post";
  priorStatsSeason: string;
  scoringMode: "unknown";
  /** Revalidation intervals; failed refreshes may serve older last-good values. */
  cacheRevalidateSeconds: { league: 300; rosters: 300; players: 300; stats: 86400 };
  sourceUpdatedAt: null;
  availability: { players: "available" | "unavailable"; priorStats: "available" | "unavailable"; currentStats: "available" | "unavailable" | "preseason_not_started" };
  teams: { teamId: string; name: string; rosterSize: number; namedPlayers: number; priorStatsPlayers: number; currentStatsPlayers: number; startersKnown: boolean; reserveKnown: boolean; taxiKnown: boolean }[];
};

/** Bounded server projection. Clients cannot supply roster/player/stat evidence. */
export type AiLeagueRosterInput = Omit<AiLeagueContextMetadata, "hash" | "teams"> & {
  scoring: Record<string, number>;
  teams: {
    teamId: string;
    name: string;
    starters: string[] | null;
    reserve: string[] | null;
    taxi: string[] | null;
    players: { id: string; name: string | null; age: number | null; position: string | null; prior: { fppg: number; games: number } | null; current: { fppg: number; games: number } | null }[];
  }[];
};

export type AiSnapshotMetadata = {
  hash: string;
  model: string;
  promptVersion: string;
  capturedAt: string;
  cutoffAt: string;
  /** Null when Sleeper's leg, rather than an unverified calendar, bounds a preview. */
  startsAt: string | null;
  endsAt: string | null;
  statsSeason: string;
  scoringMode: AiWeeklyInput["scoringMode"];
  baselineVersion: string;
  comparison?: "preseason_lineup_preview" | "weekly_lineup_preview";
  sourceLeg?: number;
};

/** Immutable generation provenance. Historical reads do not use today's policy. */
export type AiGenerationManifest = {
  schemaVersion: 1 | 2;
  model: string;
  promptVersion: string;
  instructions: string;
  baselineVersion: "prior-starter-ppg-v1" | "prior-observed-starter-ppg-v2";
};

export type AiFailureStatus = "unavailable" | "invalid" | "unauthenticated" | "rate_limited" | "busy" | "refused" | "timeout";
export type AiDecideResponse =
  | { status: "ready"; result: AiDecisionResult }
  | { status: AiFailureStatus; code: string; message: string; retryAfterSeconds?: number };

/** This comparison has no schedule adjustment and is not a weekly score forecast. */
export type AiBaseline = {
  version: string;
  label: string;
  teamValues: { teamId: string; value: number | null }[];
  pick: string | null;
};

export type AiWeeklyPick = {
  matchupId: string;
  teamIds: [string, string];
  status: "ready" | "unavailable";
  message: string;
  result: AiDecisionResult | null;
  evidence: string[];
  baseline: AiBaseline | null;
};

export type AiWeeklySlate = {
  leagueId: string;
  season: string;
  week: number;
  status: "ready" | "unavailable" | "stale";
  message: string;
  generatedAt: string | null;
  matchups: AiWeeklyPick[];
  snapshot: AiSnapshotMetadata | null;
};

export type AiDecidesData = {
  /** Present only while the separately reviewed one-shot Week 1 refresh is enabled. */
  week1Refresh?: { status: "available" | "sealed" | "published" | "unavailable"; message: string };
  availability: { status: "available" | "unavailable"; code: string; message: string };
  weekly: AiWeeklySlate;
};

/** Inputs retained once per week. No post-cutoff inputs or observed outcomes. */
export type AiWeeklyInput = {
  leagueId: string;
  season: string;
  week: number;
  capturedAt: string;
  cutoffAt: string;
  startsAt: string | null;
  endsAt: string | null;
  phase: "pre" | "regular" | "post";
  scoringMode: "lock_in" | "game_pick" | "unknown";
  scoring: Record<string, number>;
  starterSlots: string[];
  statsSeason: string;
  statsAvailableAt: string;
  /** Supplied only by the server's public-source loader. No numeric mode mapping. */
  preview?: {
    kind: "lineup_strength";
    sourceLeg: number;
    seasonStartDate: string;
    gameModeCode: number | null;
  };
  matchups: { matchupId: string; teamIds: [string, string] }[];
  teams: {
    teamId: string;
    starters: string[];
    reserve: string[];
    taxi: string[];
    eligibilityKnown: boolean;
    players: { playerId: string; priorFantasyPpg: number | null; priorGames: number | null }[];
  }[];
};

/** Append-only evaluation record, deliberately outside the prediction snapshot. */
export type AiWeeklyOutcome = {
  matchupId: string;
  recordedAt: string;
  final: true;
  teamPoints: { teamId: string; points: number }[];
};

/** Publication is an operator operation; public reads never generate. */
export type AiWeeklyPublishResponse =
  | { status: "ready"; weekly: AiWeeklySlate }
  | Exclude<AiDecideResponse, { status: "ready" }>;

/** Minimal public-source context for the next pre-generated lineup preview. */
export type AiPublicationContext = {
  leagueId: string;
  season: string;
  phase: "pre" | "regular";
  leg: number;
  week: number;
  seasonStartDate: string;
  statsSeason: string;
  gameModeCode: number | null;
};
