// One focused offline caller smoke. Uses an existing Playwright installation.
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
assert.ok(process.env.SHELL_TEST_PLAYWRIGHT, "Supply an already installed Playwright; do not install");
const { chromium } = await import(pathToFileURL(process.env.SHELL_TEST_PLAYWRIGHT).href);
const evidence = path.resolve(process.env.RETAINED_HISTORY_EVIDENCE ?? "/tmp/goat-retained-history-smoke");
await mkdir(evidence, { recursive: true });
const results = { checks: [], pageErrors: [], externalRequestsBlocked: 0, applicationResponses: "synthetic only" };
let log = "", browser;
const server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "src/test/retained-history", "--config", "src/test/retained-history/vite.config.mts"],
  { cwd: repo, env: { PATH: process.env.PATH, TMPDIR: "/tmp", LANG: "en_US.UTF-8", TZ: "UTC" }, stdio: ["ignore", "pipe", "pipe"] });
for (const stream of [server.stdout, server.stderr]) stream.on("data", chunk => { log += chunk.toString(); });
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
const check = label => { results.checks.push(label); console.log(label); };
try {
  for (let i = 0; i < 100 && !log.match(/http:\/\/127\.0\.0\.1:\d+/); i++) await pause(100);
  const origin = log.match(/http:\/\/127\.0\.0\.1:\d+/)?.[0];
  assert.ok(origin, log);
  browser = await chromium.launch({ headless: true, ...(process.env.SHELL_TEST_CHROME ? { executablePath: process.env.SHELL_TEST_CHROME } : {}) });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, reducedMotion: "reduce" });
  await context.route("**/*", route => {
    const request = route.request();
    if (new URL(request.url()).hostname !== "127.0.0.1" || request.method() !== "GET") {
      results.externalRequestsBlocked += 1; return route.abort();
    }
    return route.continue();
  });
  const page = await context.newPage();
  page.on("pageerror", error => results.pageErrors.push(error.message));
  page.setDefaultTimeout(6000);
  await page.goto(origin, { waitUntil: "networkidle" });
  const calls = () => page.evaluate(() => window.historyFixture.requests.map(r => ({ url: r.url, aborted: r.signal?.aborted })));
  const alpha = page.getByRole("button", { name: "Price history for Synthetic Alpha", exact: true });
  await alpha.click();
  await page.getByRole("heading", { name: "Retained history", exact: true }).waitFor();
  assert.equal((await calls()).length, 0);
  await page.getByRole("button", { name: "Load retained history", exact: true }).click();
  const recorded = page.getByRole("region", { name: "Recorded snapshots", exact: true });
  const modeled = page.getByRole("region", { name: "Reconstructed estimates", exact: true });
  await recorded.getByText(/2 retained records loaded/).waitFor();
  await modeled.getByText(/1 retained records loaded/).waitFor();
  assert.equal((await calls()).length, 2);
  assert.ok((await calls()).every(call => call.url.includes("limit=200") && !call.url.includes("cursor=")));
  assert.equal(await recorded.locator("svg path").count(), 0);
  assert.equal(await modeled.locator("svg path").count(), 1);
  await recorded.getByRole("slider").focus();
  await page.keyboard.press("ArrowRight");
  await recorded.getByText(/Record observed-b/).waitFor();
  assert.equal(await recorded.locator("time").textContent(), "2026-10-08T01:41:52.104607");
  assert.match(await recorded.textContent(), /8438 cents/);
  check("Selected player -> actual client adapter -> two bounded synthetic pages; raw native ties/cents inspectable, source plots separate");
  await recorded.getByRole("button", { name: "Load more recorded snapshots", exact: true }).click();
  await recorded.getByText(/3 retained records loaded; retained range exhausted/).waitFor();
  assert.equal((await calls()).length, 3);
  assert.ok((await calls())[2].url.includes("cursor=observed_more"));
  assert.match(await recorded.textContent(), /Coverage remains unknown/);
  const graph = await recorded.locator("svg").boundingBox();
  await page.mouse.click(graph.x + graph.width * .96, graph.y + graph.height / 2);
  await recorded.getByText(/Record observed-c/).waitFor();
  check("Manual paging appends every record without fetching the other source or claiming completeness");
  for (const width of [390, 1200]) {
    await page.setViewportSize({ width, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `No overflow at ${width}px`);
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: path.join(evidence, "retained-history-390.png"), fullPage: true });
  check("Focused 390px/desktop bounds smoke passes with the existing chart layout preserved");
  await page.locator("#response-mode").selectOption("unavailable");
  await page.getByRole("button", { name: "Load retained history", exact: true }).click();
  await recorded.getByText("This source is temporarily unavailable.", { exact: true }).waitFor();
  assert.equal(await recorded.locator("svg").count(), 0);
  assert.ok(!(await recorded.textContent()).includes("No retained records"));
  await page.locator("#response-mode").selectOption("ready");
  await recorded.getByRole("button", { name: "Retry recorded snapshots", exact: true }).click();
  await recorded.getByText(/2 retained records loaded/).waitFor();
  check("503 unavailable remains distinct from empty; explicit retry recovers");
  await page.locator("#response-mode").selectOption("unavailable");
  await recorded.getByRole("button", { name: "Load more recorded snapshots", exact: true }).click();
  await recorded.getByText(/2 earlier loaded records remain visible/).waitFor();
  assert.equal(await recorded.locator("svg circle").count(), 3);
  await page.getByRole("button", { name: "Close player detail", exact: true }).click();
  assert.equal(await alpha.evaluate(e => e === document.activeElement), true);
  check("Later-page failure preserves earlier records as partial; Close restores focus from error");
  await page.locator("#response-mode").selectOption("drift");
  await alpha.click();
  await page.getByRole("button", { name: "Load retained history", exact: true }).click();
  await modeled.getByText(/1 retained records loaded/).waitFor();
  await modeled.getByRole("button", { name: "Load more reconstructed estimates", exact: true }).click();
  await modeled.getByText(/Reconstruction changed/).waitFor();
  assert.equal(await modeled.locator("svg").count(), 0);
  assert.equal(await modeled.locator("time").count(), 0);
  await page.locator("#response-mode").selectOption("ready");
  await modeled.getByRole("button", { name: "Restart reconstructed estimates", exact: true }).click();
  await modeled.getByText(/1 retained records loaded/).waitFor();
  assert.ok(!(await calls()).at(-1).url.includes("cursor="));
  check("409 clears the old modeled sequence and restarts explicitly without mixing generations");
  await page.locator("#response-mode").selectOption("pending");
  const before = (await calls()).length;
  await page.getByRole("button", { name: "Load retained history", exact: true }).click();
  await page.waitForFunction(count => window.historyFixture.requests.length === count + 2, before);
  await page.getByLabel("From", { exact: true }).fill("2026-01-01");
  await page.getByLabel("Before", { exact: true }).fill("2026-11-01");
  await page.getByRole("button", { name: "Load retained history", exact: true }).click();
  await page.waitForFunction(count => window.historyFixture.requests.length === count + 4, before);
  assert.ok((await calls()).slice(before, before + 2).every(r => r.aborted));
  await page.getByRole("button", { name: "Price history for Synthetic Beta", exact: true }).click();
  await page.getByRole("heading", { name: "Inside the price: Synthetic Beta", exact: true }).waitFor();
  assert.ok((await calls()).slice(before).every(r => r.aborted));
  await page.getByRole("button", { name: "Resolve pending fixture", exact: true }).click();
  assert.equal(await page.getByRole("heading", { name: "Recorded snapshots", exact: true }).count(), 0);
  await page.locator("#response-mode").selectOption("pending");
  const closing = (await calls()).length;
  await page.getByRole("button", { name: "Load retained history", exact: true }).click();
  await page.waitForFunction(count => window.historyFixture.requests.length === count + 2, closing);
  await page.getByRole("button", { name: "Close player detail", exact: true }).click();
  assert.ok((await calls()).slice(closing).every(r => r.aborted));
  await page.getByRole("button", { name: "Resolve pending fixture", exact: true }).click();
  assert.equal(await page.getByRole("heading", { name: "Retained history", exact: true }).count(), 0);
  check("Range/player replacement and Close abort pending reads; late fake responses cannot reopen stale history");
  assert.deepEqual(results.pageErrors, []);
  check("No browser runtime errors; no live application/database/provider calls");
} finally {
  await browser?.close();
  server.kill("SIGTERM");
  await writeFile(path.join(evidence, "results.json"), JSON.stringify(results, null, 2) + "\n");
  await writeFile(path.join(evidence, "vite.log"), log);
}
