/**
 * arcade domain — the shared language for accounts, games, and rewards.
 *
 * This is the second bounded context of the site. The league context
 * (`src/domain/`) is read-only Sleeper data; the arcade context is the
 * site's own write world: who the managers are, what they played, what
 * they won. The two contexts share nothing except the team id — a
 * SiteUser points at a Sleeper roster via `teamId`, but never imports
 * league types. That keeps the arcade testable and portable even if the
 * league data source ever changes.
 *
 * All definitions are `type` (project rule 10). Doc comments are mandatory.
 */

/** A league manager with a site account. One account per Sleeper team. */
export type SiteUser = {
  /** UUID, generated by the database. */
  id: string;
  /** Sleeper roster_id of the team this account owns. Unique. */
  teamId: string;
  /** Display name — the team's name at claim time. */
  displayName: string;
  /** When the account was created. */
  createdAt: Date;
};

/**
 * A single-use invite code that binds a Sleeper team to a site account.
 *
 * Aidan (commissioner) generates one code per team and distributes it
 * privately. Codes are plain strings on purpose: they work from any
 * device, and claiming from a phone then playing on a laptop just works.
 * A code dies the moment it is consumed.
 */
export type InviteCode = {
  /** The code itself: a 6-digit number, e.g. "482910". Unique. */
  code: string;
  /** Sleeper roster_id this code claims. */
  teamId: string;
  /** Id of the user who consumed the code. Null until claimed. */
  usedBy: string | null;
  /** When the code was consumed. Null until claimed. */
  usedAt: Date | null;
  /** When the code was issued. */
  createdAt: Date;
};

/**
 * A login session. The cookie holds the raw token; the database holds
 * only its SHA-256 hash, so a database read never yields a live session.
 */
export type GameSession = {
  /** SHA-256 hex of the token stored in the `gh_session` cookie. */
  tokenHash: string;
  /** The logged-in user. */
  userId: string;
  /** Sessions are long-lived: "remember me" is the default (90 days). */
  expiresAt: Date;
  createdAt: Date;
};

/** A playable game registered on the site. */
export type Game = {
  /** Stable slug, e.g. "free-throw". Used in URLs and score records. */
  id: string;
  /** Human name, e.g. "Free Throw Shootout". */
  name: string;
  /** One-line pitch shown on the game card. */
  description: string;
  /** Emoji icon for the game card. */
  icon: string;
  /** Games ship "coming-soon" first; the registry is the pattern. */
  status: "live" | "coming-soon";
  /**
   * How the game is played, shown on the detail page. Plain text, short.
   */
  howToPlay: string;
};

/**
 * One recorded score for a game. Scores are scoped to a league week so
 * every game gets a weekly leaderboard and a weekly winner.
 */
export type GameScore = {
  /** UUID. */
  id: string;
  /** Game slug, matches `Game.id`. */
  gameId: string;
  /** Who played. */
  userId: string;
  /** Higher is better. Game-specific units (points, makes, etc.). */
  score: number;
  /** League week label, e.g. "2026-W06". */
  week: string;
  createdAt: Date;
};

/** One row of a weekly leaderboard, with the rank already computed. */
export type LeaderboardEntry = {
  rank: number;
  score: number;
  /** Display name of the scorer. */
  displayName: string;
  /** Sleeper team id, for avatars/links. */
  teamId: string;
  /** True when this entry belongs to the currently logged-in user. */
  isCurrentUser: boolean;
};

/**
 * A FAAB reward owed to a manager. The site is the source of truth for
 * *who earned what*; settlement happens by the commissioner because the
 * Sleeper API does not expose FAAB adjustments. A reward starts pending
 * and flips to settled once Aidan applies it.
 */
export type Reward = {
  /** UUID. */
  id: string;
  /** Who earned it. */
  userId: string;
  /** Display name, denormalized for simple rendering. */
  displayName: string;
  /** Game slug that produced the reward. */
  gameId: string;
  /** League week the reward was earned in. */
  week: string;
  /** FAAB dollars owed. */
  amountFaab: number;
  /** False until the commissioner settles it. */
  settled: boolean;
  createdAt: Date;
};
