/**
 * arcade domain — the shared language for accounts, games, and rewards.
 *
 * This is the second bounded context of the site. The league context
 * (`src/domain/`) is read-only Sleeper data; the arcade context is the
 * site's own write world: who the managers are, what they played, what
 * they won. The two contexts share nothing except the team id — a
 * SiteUser points at a Sleeper roster via `teamId`, but never imports
 * league types. That keeps the arcade testable and portable even if the
 * league data source ever changes.
 *
 * All definitions are `type` (project rule 10). Doc comments are mandatory.
 */

/** A league manager with a site account. One account per Sleeper team. */
export type SiteUser = {
  /** UUID, generated by the database. */
  id: string;
  /** Sleeper roster_id of the team this account owns. Unique. */
  teamId: string;
  /** Display name — the team's name at claim time. */
  displayName: string;
  /** When the account was created. */
  createdAt: Date;
};

/**
 * A single-use invite code that binds a Sleeper team to a site account.
 *
 * Aidan (commissioner) generates one code per team and distributes it
 * privately. Codes are plain strings on purpose: they work from any
 * device, and claiming from a phone then playing on a laptop just works.
 * A code dies the moment it is consumed.
 */
export type InviteCode = {
  /** The code itself: a 6-digit number, e.g. "482910". Unique. */
  code: string;
  /** Sleeper roster_id this code claims. */
  teamId: string;
  /** Id of the user who consumed the code. Null until claimed. */
  usedBy: string | null;
  /** When the code was consumed. Null until claimed. */
  usedAt: Date | null;
  /** When the code was issued. */
  createdAt: Date;
};

/**
 * Input for the atomic team-claim operation.
 *
 * The store creates the account AND consumes the invite code as one
 * database operation — either both happen or neither. Password hashing
 * happens in the action before this; the store only sees the hash.
 */
export type ClaimTeamInput = {
  /** Normalized 6-digit invite code. */
  code: string;
  /** Display name for the new account. */
  displayName: string;
  /** bcrypt hash. Raw passwords never reach the store. */
  passwordHash: string;
};

/**
 * Typed result of the atomic team-claim operation.
 *
 * `invalid_code`: no such code exists. `already_used`: the code was
 * already consumed. `team_claimed`: another account already owns this
 * team. Expected conflicts never throw — only infrastructure failures do.
 */
export type ClaimResult =
  | { ok: true; user: SiteUser }
  | { ok: false; reason: "invalid_code" | "already_used" | "team_claimed" };

/**
 * A login session. The cookie holds the raw token; the database holds
 * only its SHA-256 hash, so a database read never yields a live session.
 */
export type GameSession = {
  /** SHA-256 hex of the token stored in the `gh_session` cookie. */
  tokenHash: string;
  /** The logged-in user. */
  userId: string;
  /** Sessions are long-lived: "remember me" is the default (90 days). */
  expiresAt: Date;
  createdAt: Date;
};

/** A registered game or planned league competition. */
export type Game = {
  /** Stable slug, e.g. "free-throw". Used in URLs and score records. */
  id: string;
  /** Human name, e.g. "Free Throw Shootout". */
  name: string;
  /** One-line pitch shown on the game card. */
  description: string;
  /** Emoji icon for the game card. */
  icon: string;
  /** League competition status. Public practice can be available separately. */
  status: "live" | "coming-soon";
  /** Present only when a real play implementation is available at this game's route. */
  play?: {
    mode: "practice" | "competition";
    /** A screenshot of the actual implementation, never a placeholder. */
    preview: { src: string; alt: string };
    touchInstructions: string;
  };
  /**
   * Why a coming-soon game isn't playable yet, and when it opens — in
   * the league's voice, never a bare "coming soon". Shown on the game
   * card and detail page. Omit for live games.
   */
  launchNote?: string;
  /**
   * How the game is played, shown on the detail page. Plain text, short.
   */
  howToPlay: string;
};

/** A registry entry with an implemented launch, independent of reward readiness. */
export type PlayableGame = Game & { play: NonNullable<Game["play"]> };

/**
 * One recorded score for a game. Scores are scoped to a league week so
 * every game gets a weekly leaderboard and a weekly winner.
 */
export type GameScore = {
  /** UUID. */
  id: string;
  /** Game slug, matches `Game.id`. */
  gameId: string;
  /** Who played. */
  userId: string;
  /** Higher is better. Game-specific units (points, makes, etc.). */
  score: number;
  /** League week label, e.g. "2026-W06". */
  week: string;
  createdAt: Date;
};

/** One row of a weekly leaderboard, with the rank already computed. */
export type LeaderboardEntry = {
  rank: number;
  score: number;
  /** Display name of the scorer. */
  displayName: string;
  /** Sleeper team id, for avatars/links. */
  teamId: string;
  /** True when this entry belongs to the currently logged-in user. */
  isCurrentUser: boolean;
};

/**
 * A FAAB reward owed to a manager. The site is the source of truth for
 * *who earned what*; settlement happens by the commissioner because the
 * Sleeper API does not expose FAAB adjustments. A reward starts pending
 * and flips to settled once Aidan applies it.
 */
export type Reward = {
  /** UUID. */
  id: string;
  /** Who earned it. */
  userId: string;
  /** Display name, denormalized for simple rendering. */
  displayName: string;
  /** Game slug that produced the reward. */
  gameId: string;
  /** League week the reward was earned in. */
  week: string;
  /** FAAB dollars owed. */
  amountFaab: number;
  /** False until the commissioner settles it. */
  settled: boolean;
  createdAt: Date;
};

/**
 * One game as the arcade hub shows it: the registry entry plus this
 * week's live state — the current leader and the viewer's own best
 * score. Built by getArcadeHubData in src/data/arcade.ts.
 */
export type GameHubSummary = {
  /** The game, from the registry. */
  game: Game;
  /** This week's top entry, with isCurrentUser resolved. Null when empty. */
  leader: LeaderboardEntry | null;
  /** The viewer's best score this week. Null when logged out or scoreless. */
  myBest: number | null;
};
